### PR TITLE
Gemfile environments updates

### PR DESCRIPTION
**Pull request by jmcoimbra**
* factory_girl_rails is test only
* fixing capybara and factory_girl_rails to a version
* including web-console and spring to development
* buybug gem is available for test and development

### CODE REVIEW

**Comment by gvillalta99** [comment]
@jmcoimbra I'm not sure about the `spring` gem.
It is used to reload the Rails application that is running in your machine, so, if you running the Rails application on Docker it won't be used.

We can keep it, but, probably, it is not the best workflow for our team right now.

**Comment by jmcoimbra** [comment]
Hey good point, I've been using it in my local development, without Docker.
I will remove and feel better about it :8ball:

**Comment by gvillalta99** [comment]
Cool @jmcoimbra !
Let's merge this?

**Comment by jmcoimbra** [comment]
Go for it!
Em 8 de jun de 2016 2:12 PM, "gvillalta99" <notifications@github.com>
escreveu:

**Pull request merged**
